# Site settings
title:            BIMstandards
description:      Bonnes pratiques des standards openBIM, pour des échanges opérationnels au quotidien !
keywords:         standards, BIM, openBIM, interopérabilité, BuildingSMART, IFC, IDM, MVD, COBie, BCF, bSDD, gbXML, BIMétré
author:           Alexandre Grignon
url:              "http://bimstandards.fr"
repository:       bimstandards/bimstandards

# Versions
version:          v0.1.0-beta.13
latest_update:    04/12/2017

# Build settings
markdown:         kramdown
highlighter:      rouge
exclude:          [vendor]

# Collections
collections:
  pages: {output: true, permalink: '/:path/'}
  echanger-en-bim: {output: true, permalink: '/echanger-en-bim/:path/'}
  travailler-avec-les-ifc: {output: true, permalink: '/travailler-avec-les-ifc/:path/'}
  standards: {output: true, permalink: '/standards/:path/'}
  autocontrole: {output: true, permalink: '/autocontrole/:path/'}
  archicad: {output: true, permalink: '/archicad/:path/'}
  revit: {output: true, permalink: '/revit/:path/'}
  ressources: {output: true, permalink: '/ressources/:path/'}
  fiches: {output: true, permalink: '/echanger-en-bim/fiches-echanges/:path/'}
  
# Assets
sass:
  style: compressed

# Gems (Jekyll plugins)
plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-feed

# Pour activer github-metadata : https://github.com/jekyll/github-metadata
# $ JEKYLL_GITHUB_TOKEN=123abc [bundle exec] jekyll serve
