# Site settings
title:            BIMstandards
description:      Plateforme collaborative sur les standards d'échanges et l'interopérabilité BIM
keywords:         standards, BIM, openBIM, interopérabilité, BuildingSMART, France, Mediaconstruct, IFC, IDM, MVD, COBie, BCF, bSDD, gbXML, BIMétré
author:           Alexandre Grignon
url:              "https://bimstandards.fr"
repository:       bimstandards/bimstandards

# Versions
version:          v1.0.0
latest_update:    17/12/2017

# Build settings
markdown:         kramdown
highlighter:      rouge
exclude:          [vendor]

# Collections
collections:
  pages: {output: true, permalink: '/:path/'}
  vous-informer: {output: true, permalink: '/vous-informer/:path/'}
  data-bim: {output: true, permalink: '/data-bim/:path/'}
  process-bim: {output: true, permalink: '/process-bim/:path/'}
  travailler-avec-les-ifc: {output: true, permalink: '/travailler-avec-les-ifc/:path/'}
  echanger-en-bim: {output: true, permalink: '/echanger-en-bim/:path/'}
  fiches: {output: true, permalink: '/echanger-en-bim/fiches-echanges/:path/'}
  cv-openbim: {output: true, permalink: '/echanger-en-bim/cv-openbim/:path/'}
  formation-rd: {output: true, permalink: '/formation-rd/:path/'}
  
# Assets
sass:
  style: compressed

# Gems (Jekyll plugins)
plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-redirect-from

# Pour activer github-metadata : https://github.com/jekyll/github-metadata
# $ JEKYLL_GITHUB_TOKEN=123abc [bundle exec] jekyll serve
